### ISSUE TITLE
PHP errors

### ISSUE THREAD

**Issue by oliversum-ch** [invoiceninja/wordpress#1]
Hey @hillelcoren 
I get this error once I access the admin page:

> Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, string given in /wp-content/plugins/invoiceninja/app/Controllers/SettingsController.php:407](/wp-content/plugins/invoiceninja/app/Controllers/SettingsController.php:407)
> Stack trace:
> #0 /wp-content/plugins/invoiceninja/app/Controllers/SettingsController.php(407)](/wp-content/plugins/invoiceninja/app/Controllers/SettingsController.php(407)): in_array('ah-beirat', '')
> #1 /wp-admin/includes/template.php(1836)](/wp-admin/includes/template.php(1836)): App\Controllers\SettingsController->App\Controllers\{closure}(Array)
> #2 /wp-admin/includes/template.php(1790)](/wp-admin/includes/template.php(1790)): do_settings_fields('invoiceninja_cl...', 'invoiceninja_ad...')
> #3 /wp-content/plugins/invoiceninja/templates/settings.php(25)](/wp-content/plugins/invoiceninja/templates/settings.php(25)): do_settings_sections('invoiceninja_cl...')
> #4 /wp-content/plugins/invoiceninja/app/Controllers/SettingsController.php(81)](/wp-content/plugins/invoiceninja/app/Controllers/SettingsController.php(81)): require_once('/home_pr6/i/n/i...')
> #5 /wp-includes/class-wp-hook.php(324)](/wp-includes/class-wp-hook.php(324)): App\Controllers\SettingsController->App\Controllers\{closure}('')
> #6 /wp-includes/class-wp-hook.php(348)](/wp-includes/class-wp-hook.php(348)): WP_Hook->apply_filters('', Array)
> #7 /wp-includes/plugin.php(517)](/wp-includes/plugin.php(517)): WP_Hook->do_action(Array)
> #8 /wp-admin/admin.php(259)](/wp-admin/admin.php(259)): do_action('toplevel_page_i...')
> #9 {main}
>   thrown

This WordPress installation runs on PHP 8.1 (I can't migrate to PH P8.2 due to other plugin incompatibilities).
'ah-beirat' in Error #0 is a custom user role I created, that might be a first clue. I will look into it.

**Comment by hillelcoren** [comment]
Thanks, I'll look into it.

**Comment by hillelcoren** [comment]
I'm not able to replicate this but I've added a check catch the error.

I'll build a new release with the fix.
