### ISSUE TITLE
1.0.7 doesn't install

### ISSUE THREAD

**Issue by JamesGrant88** [invoiceninja/wordpress#2]
Hi, I added 1.0.7 to my website and while it showed in active plugins the settings menu wasn't there.

I tried 1.0.6 and that worked fine.

**Comment by hillelcoren** [comment]
Hi,

Are there any errors in the logs when trying to activate the plugin?

**Comment by JamesGrant88** [comment]
> Hi,
> 
> Are there any errors in the logs when trying to activate the plugin?

The plugin activates fine, it just doesn't appear in the menu. It only appears when installing 1.0.7

**Comment by hillelcoren** [comment]
Hmm.. I'm not sure, the changes between .6 and .7 and very minor. 

When you activate the plugin you should see a 'Settings' link, if it's there you can click it to view the plugin settings.

**Comment by CodeShakingSheep** [comment]
> > Hi,
> > Are there any errors in the logs when trying to activate the plugin?
> 
> The plugin activates fine, it just doesn't appear in the menu. It only appears when installing 1.0.7

I had this problem as well when I had renamed the ZIP file and uploaded it with another name than "invoiceninja.zip". Try uploading the ZIP file with the original name. Then it should work fine.

**Comment by JamesGrant88** [comment]
> > > Hi,
> > > Are there any errors in the logs when trying to activate the plugin?
> > 
> > 
> > The plugin activates fine, it just doesn't appear in the menu. It only appears when installing 1.0.7
> 
> I had this problem as well when I had renamed the ZIP file and uploaded it with another name than "invoiceninja.zip". Try uploading the ZIP file with the original name. Then it should work fine.

Thanks - I just did this making sure there was no rename and its worked!

Mac has an habit of uncompressing right away when downloading so you have to rezip and not sure if I made a change along the way.

**Comment by hillelcoren** [comment]
Thanks for the update, glad to hear it's working!

We've submitted the plugin to the WordPress repo but there's a long wait for reviews, it should eventually make installing/updating much simpler.
