### ISSUE TITLE
Invoice Ninja Tab/Icon not displaying

### ISSUE THREAD

**Issue by pierrehunt** [invoiceninja/wordpress#6]
I installed the plugin on the latest Wordpress and Invoice Ninja is not displaying

I then downloaded an older version of WordPress V6.0.0 and did a complete new install with a clean database and the plugin still does not appear.

Installed on Cpanel with Cloudlinux backend - so not sure if some dependencies need to be activated.

Hope you can help

Pierre
![8ecd044e-d36c-4dff-b1af-429952298bc6](https://github.com/user-attachments/assets/a2c34628-efc8-44b9-9dc0-f92657481e69)

![25cea27e-e4ec-4bd2-8448-141d80cc5dd0](https://github.com/user-attachments/assets/41db3e96-a013-4a4e-879b-563fe75b691b)

**Comment by pierrehunt** [comment]
![download (1)](https://github.com/user-attachments/assets/82c0837e-1510-4ca1-a2e2-96629eea9b57)

**Comment by hillelcoren** [comment]
It should be available from the plugin store within the next few days which may help

**Comment by hillelcoren** [comment]
https://wordpress.org/plugins/invoiceninja/

**Comment by pierrehunt** [comment]
Super - it is working like a charm now

Thank you for this amazing piece of coding Hillel

**Comment by hillelcoren** [comment]
Glad to hear it, thanks for the update!

If you'd consider leaving a review on the plugin it would be very much appreciated, we have none yet...

Also, let us know what other features you'd like us to add.
